import { useEffect, useMemo } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import type { UsuarioUI } from '../../types';

interface Carnet {
    id: number;
    usuario_id: number;
    codigo_carnet: string;
    codigo_qr: string;
    fecha_expedicion: string;
    fecha_vencimiento: string;
    estado: 'activo' | 'vencido' | 'suspendido';
}   

interface CarnetFormProps {
    carnet: Carnet | null;
    users: UsuarioUI[];
    existingCarnets?: Carnet[]; // Para generar código único
    onSubmit: (carnetData: any) => void;
    onCancel: () => void;
}

const carnetSchema = z.object({
    usuario_id: z.number().int().positive('Usuario requerido'),
    codigo_carnet: z.string().min(3, 'Código debe tener al menos 3 caracteres'),
    fecha_expedicion: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Formato de fecha inválido'),
    fecha_vencimiento: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Formato de fecha inválido'),
    estado: z.enum(['activo', 'vencido', 'suspendido']),
}).refine((data) => {
    const expedicion = new Date(data.fecha_expedicion);
    const vencimiento = new Date(data.fecha_vencimiento);
    return vencimiento > expedicion;
}, {
    message: 'La fecha de vencimiento debe ser posterior a la fecha de expedición',
    path: ['fecha_vencimiento'],
});

type CarnetFormData = z.infer<typeof carnetSchema>;

/**
 * Genera un código de carnet automático siguiendo el patrón: CARN-YYYY-XXX
 * Ejemplo: CARN-2025-001, CARN-2025-002, etc.
 */
const generateCarnetCode = (existingCarnets: Carnet[] = []): string => {
    const currentYear = new Date().getFullYear();
    const prefix = `CARN-${currentYear}-`;
    
    // Buscar el último número usado para este año
    const codesThisYear = existingCarnets
        .filter(c => c.codigo_carnet.startsWith(prefix))
        .map(c => {
            const match = c.codigo_carnet.match(new RegExp(`${prefix}(\\d+)`));
            return match ? parseInt(match[1], 10) : 0;
        });
    
    const nextNumber = codesThisYear.length > 0 
        ? Math.max(...codesThisYear) + 1 
        : 1;
    
    return `${prefix}${String(nextNumber).padStart(3, '0')}`;
};

export const CarnetForm = ({ carnet, users, existingCarnets = [], onSubmit, onCancel }: CarnetFormProps) => {
    // Generar código automático solo para nuevos carnets
    const autoGeneratedCode = useMemo(() => {
        if (carnet) return carnet.codigo_carnet; // Si es edición, usar el código existente
        return generateCarnetCode(existingCarnets);
    }, [carnet, existingCarnets]);

    const {
        register,
        handleSubmit,
        formState: { errors, isSubmitting },
        reset,
        setValue,
    } = useForm<CarnetFormData>({
        resolver: zodResolver(carnetSchema),
        defaultValues: {
            usuario_id: carnet?.usuario_id || ('' as any),
            codigo_carnet: autoGeneratedCode,
            fecha_expedicion: carnet?.fecha_expedicion || new Date().toISOString().split('T')[0],
            fecha_vencimiento: carnet?.fecha_vencimiento || '',
            estado: carnet?.estado || 'activo',
        },
        mode: 'onBlur',
    });

    useEffect(() => {
        const code = carnet ? carnet.codigo_carnet : generateCarnetCode(existingCarnets);
        reset({
            usuario_id: carnet?.usuario_id || ('' as any),
            codigo_carnet: code,
            fecha_expedicion: carnet?.fecha_expedicion || new Date().toISOString().split('T')[0],
            fecha_vencimiento: carnet?.fecha_vencimiento || '',
            estado: carnet?.estado || 'activo',
        });
        // Actualizar el código automáticamente si es un nuevo carnet
        if (!carnet) {
            setValue('codigo_carnet', code);
        }
    }, [carnet, reset, existingCarnets, setValue]);

    const onFormSubmit = (data: CarnetFormData) => {
        // Generar código QR automáticamente si no existe
        const codigo_qr = carnet?.codigo_qr || `QR-${data.codigo_carnet}-${Date.now()}`;
        
        onSubmit({
            ...data,
            codigo_qr,
        });
    };

    return (
        <form onSubmit={handleSubmit(onFormSubmit)} className="space-y-4">
            <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                    Usuario <span className="text-red-500">*</span>
                </label>
                <select
                    {...register('usuario_id', { valueAsNumber: true })}
                    disabled={!!carnet}
                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 disabled:bg-gray-100 ${
                        errors.usuario_id ? 'border-red-500' : 'border-gray-300'
                    }`}
                >
                    <option value="">Seleccione un usuario</option>
                    {users.map((user) => (
                        <option key={user.id} value={user.id}>
                            {user.name} ({user.email}) - {user.rol}
                        </option>
                    ))}
                </select>
                {errors.usuario_id && (
                    <p className="text-xs text-red-600 mt-1">{errors.usuario_id.message}</p>
                )}
            </div>

            <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                    Código de Carnet <span className="text-red-500">*</span>
                    {!carnet && (
                        <span className="text-xs text-gray-500 ml-2">(Generado automáticamente)</span>
                    )}
                </label>
                <input
                    type="text"
                    {...register('codigo_carnet')}
                    disabled={!carnet} // Solo editable si es edición
                    readOnly={!carnet} // Solo lectura para nuevos carnets
                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                        errors.codigo_carnet ? 'border-red-500' : 'border-gray-300'
                    } ${!carnet ? 'bg-gray-50 text-gray-600 cursor-not-allowed' : ''}`}
                    placeholder="CARN-2025-001"
                />
                {errors.codigo_carnet && (
                    <p className="text-xs text-red-600 mt-1">{errors.codigo_carnet.message}</p>
                )}
                {!carnet && !errors.codigo_carnet && (
                    <p className="text-xs text-green-600 mt-1">
                        ✓ Código generado automáticamente: {autoGeneratedCode}
                    </p>
                )}
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                        Fecha de Expedición <span className="text-red-500">*</span>
                    </label>
                    <input
                        type="date"
                        {...register('fecha_expedicion')}
                        className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                            errors.fecha_expedicion ? 'border-red-500' : 'border-gray-300'
                        }`}
                    />
                    {errors.fecha_expedicion && (
                        <p className="text-xs text-red-600 mt-1">{errors.fecha_expedicion.message}</p>
                    )}
                </div>

                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                        Fecha de Vencimiento <span className="text-red-500">*</span>
                    </label>
                    <input
                        type="date"
                        {...register('fecha_vencimiento')}
                        className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                            errors.fecha_vencimiento ? 'border-red-500' : 'border-gray-300'
                        }`}
                    />
                    {errors.fecha_vencimiento && (
                        <p className="text-xs text-red-600 mt-1">{errors.fecha_vencimiento.message}</p>
                    )}
                </div>
            </div>

            <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Estado</label>
                <select
                    {...register('estado')}
                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                        errors.estado ? 'border-red-500' : 'border-gray-300'
                    }`}
                >
                    <option value="activo">Activo</option>
                    <option value="vencido">Vencido</option>
                    <option value="suspendido">Suspendido</option>
                </select>
                {errors.estado && (
                    <p className="text-xs text-red-600 mt-1">{errors.estado.message}</p>
                )}
            </div>

            <div className="flex justify-end space-x-3 pt-4">
                <button
                    type="button"
                    onClick={onCancel}
                    disabled={isSubmitting}
                    className="px-4 py-2 text-gray-600 hover:text-gray-800 font-medium transition-colors disabled:opacity-50"
                >
                    Cancelar
                </button>
                <button
                    type="submit"
                    disabled={isSubmitting}
                    className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {isSubmitting ? 'Guardando...' : carnet ? 'Actualizar' : 'Crear'} Carnet
                </button>
            </div>
        </form>
    );
};

